### ISSUE TITLE
Add async version of load-balancing Java client

### ISSUE THREAD

**Issue by nyh** [scylladb/alternator-load-balancing#8]
In https://github.com/elcallio/kraken-dynamo/blob/master/syncer/src/main/java/com/scylladb/alternator/AlternatorAsyncHttpClient.java @elcallio use AWS SDK v2's **asynchronous** (future-based) API, and added load balancing support to it. We should also add such support (and documentation for it) in the alternator-load-balancing project.

**Comment by Sylvain-Royer** [comment]
@nyh I'm wondering if this feature is production ready/is planned to get merged in sometime? We're looking to use this feature at our company.

**Comment by nyh** [comment]
Good question. @elcallio did you do anything with this recently? If not, I guess I can do this myself - should be fairly straightfoward, right @elcallio ?

**Comment by elcallio** [comment]
IIRC, the annoying thing is that you need to literally override the actual client in sdk v2, so it is somewhat more intrusive than the v1 requesthandler approach. But you should just be able to move `AlternatorAsyncHttpClient` and include it in the load balance library. You probably need to do a similar class for the sync case.

**Comment by nyh** [comment]
I don't think it really matters if we have just one artifact for both, or even the same instructions. Every user will know which instructions and/or library they need, and pick the right one.

**Comment by mykaul** [comment]
Fixed via https://github.com/scylladb/alternator-load-balancing/pull/10 ?

**Comment by elcallio** [comment]
Yes

**Comment by nyh** [comment]
Closing as solved by #10 which I just merged.

@elcallio maybe you can add at least a few lines for example how to use this new async version in java/README.md? Otherwise I fear users will have no idea how to use it.

**Comment by elcallio** [comment]
@nyh: https://github.com/scylladb/alternator-load-balancing/pull/12
